### ISSUE TITLE
Make context menu more intuitive

### ISSUE THREAD

**Issue by KonradHoeffner** [snikproject/snik-graph#113]
Investigate if the context menu can be made more intuitive, also for trackpads.
See js/contextmenu.js.

**Comment by T-P-1** [comment]
does not work in another way, maybe with a new library

**Comment by ThomasPause** [comment]
is it possible to deactivate left mouse button?
if yes, is it possible to detect mobile devices because they do not have such a button ;)

**Comment by KonradHoeffner** [comment]
Closed in favor of the later duplicate #185.
