### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/snik-graph#185]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Es ist gut, dass das Kontextmenü nun nur per rechtsklick geöffnet wird. Ich hätte nun aber auch gerne, dass es sich so verhält, wie üblicherweise zumindest unter Windows:
- nach Rechtsklick bleibt das Menu offen 
- wenn man mit der Maus dann über eine Optionen fährt (hoovert), wird die Option markiert. 
- Zur aktivierung der Option wird erneut geklickt (egal, ob mit Rechts oder mit Links)

AW

**Comment by KonradHoeffner** [comment]
Das Kontextmenü basiert auf dem Cytoscape.js plugin [cytoscape-cxtmenu](https://github.com/cytoscape/cytoscape.js-cxtmenu#cytoscape-cxtmenu). Leider ist [in der API](https://github.com/cytoscape/cytoscape.js-cxtmenu#api) kein Windows-konformes Verhalten einstellbar.

Wir könnten einen fork vom plugin erstellen und es dort ändern, das können wir gerne probieren aber das würde einen hohen Zeitaufwand bedeuten.

**Comment by KonradHoeffner** [comment]
Da das Problem auch von den BIS 21 Reviewern kritisiert wurde, werde ich das Menü durch ein normales Kontextmenü ersetzen.

**Comment by KonradHoeffner** [comment]
# Testen
## Nodes
### Base
- [ ] edit/report 
- [ ] class use 
- [ ] hide 
- [ ] set as path source 
- [ ] description 
- [ ] star 
- [ ] incoming star 
- [ ] outgoing star 
- [ ] path 
- [ ] spiderworm 

### Developer
- [ ] remove permanently 
- [ ] OntoWiki 
- [ ] debug 

### Extended
- [ ] doublestar 
- [ ] starpath 
- [ ] circle star 
- [ ] LodLive 
- [ ] move all selected here 
- [ ] close matches 
- [ ] show instances 

## Edges
- [ ] edit / report 
- [ ] hide 
- [ ] description (if it exists) 
- [ ] remove permanently 
- [ ] OntoWiki 
- [ ] debug 
- [ ] confirm link
