### ISSUE TITLE
Download der Ontologie

### ISSUE THREAD

**Issue by AlfredWinter** [snikproject/snik-graph#371]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Ich hätte gerne auf der Webseite eine Möglichkeit zum Download der Diagramme der Startseite.

**Comment by KonradHoeffner** [comment]
Im "Help"-Menü gibt es jetzt einen Eintrag "SNIK Meta Model", welcher zu einem Diagramm des Metamodells führt.
Welche Diagramme sollen noch bereitgestellt werden?

**Comment by KonradHoeffner** [comment]
Einen Link auf die Startseite gibt es auch im Menü, daher mache ich das erstmal zu. Wenn doch noch ein weiteres Diagramm von SNIK Graph aus heruntergeladen werden können soll, bitte Issue wieder öffnen.
